# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "wa-223005-pvo"
    dynamodb_table = "terraform-state-lock"
    key            = "states/wa/220530.tfstate"
    profile        = "PVO"
    region         = "us-east-1"
  }
}
